### ISSUE TITLE
Working around URL Error 503

### ISSUE THREAD

**Issue by rmac94** [evanodell/ukpolice#4]
Hi, 

I've tried to query a large custom poly, but result with the following message. Please see code below:

```
# Create large custom area
poly_big <- data.frame(
  lat = c(51.508449,51.368342,51.423457,51.512925),
  lng = c(-0.378617,-0.454862,-0.098453,-0.114220)
)
df <- ukc_crime_poly(poly_big)

#Returns error
"Request returned error code: 503"
```

I suspect this is do with: "If a custom area contains more than 10,000 crimes, the API will return a 503 status code." from the API [documentation](https://data.police.uk/docs/method/crime-street/).

I had an idea to try and replace the httr::GET withing ukpolice::ukc_get_data with httr::POST, see code below, but havent' had much success.

```
baseurl <- "https://data.police.uk/api/crimes-at-location?"


#Create string in correct format 
ukc_poly_paste <- function(data,lng,lat) {
  poly_paste <- paste(paste(data$lat, data$lng, sep = ","), collapse = ":")
  
  poly_paste
}
poly_string <- ukc_poly_paste(poly_big,"lng","lat")
date = "2020-01"

POST <- httr::POST(url = baseurl,
                   body = list(
                     poly = poly,
                     date = date
                   ))

# Returns URL Error code 404
```
My knowledge of httr::POST is relatively little, so apologies for any errors from lack of understanding.

Thanks
Ronan

**Comment by evanodell** [comment]
What is the rationale for using POST instead of GET? There is a limit of 10 000 crimes in an area. Using POST with this API might allow for unusually complex queries, but it won't get around the limit of 10 000 at a time.

**Comment by rmac94** [comment]
Sorry, 

Thanks, I wasn't sure that if by using POST you could recieve a larger request, as well as send.

I was using a simple 4 point poly in the code above as an example. However, my next plan was then to replace the simple large custom poly with multiple smaller, more detailed polys for each unit area. This however, exceeds the URL limit which is why I moved towards using POST. 

If you have any thoughts as to how to incorporate a httr::POST with the ukc_get_data, that would be really helpful.

Thanks
